# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dummyimage',
            old_name='images',
            new_name='image',
        ),
    ]
